version: "3.9"

services:
  db:
    image: postgres:14
    container_name: db
    environment:
      - DB_ENGINE="django.db.backends.postgresql"
      - POSTGRES_DB="postgres-staging"
      - POSTGRES_USER="postgres-staging"
      - POSTGRES_PASSWORD="postgres-staging"
      - POSTGRES_HOST="db"
      - POSTGRES_PORT=5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432
    restart: always
  
  crud_app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    expose:
      - 8000
    restart: always
    depends_on:
      - db

volumes:
  postgres_data: