version: "3.9"

services:
  crud_db:
    image: postgres:14
    container_name: crud_db
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=crud_db
      - POSTGRES_PORT=5545
    volumes:
      - postgres_data_fuspay:/var/lib/postgresql/data
    ports:
      - 5545:5432
    expose:
      - 5545
    command: -p 5545
    restart: always
  
  crud_app:
    build: .
    command: python manage.py runserver 0.0.0.0:9797
    volumes:
      - .:/app
    ports:
      - "9797:9797"
    expose:
      - 9797
    restart: always
    depends_on:
      - crud_db

volumes:
  postgres_data_fuspay: